version: '3.7'

services:
  signaling:
    image: robolive-signalling
    build:
      context: ./infra/playbook
      dockerfile: ./roles/signalling/Dockerfile
    container_name: signalling
    ports:
      - "9030:9030"
      - "9031:9031"
    volumes:
      - ./tmp/config:/etc/kamailio
      - ./signalling/server/engine:/etc/kamailio/engine
    networks:
        testing_net:
            ipv4_address: 169.28.1.1

  robot:
    image: robot
    build:
      context: .
      dockerfile: Dockerfile.allscala
      target: robot
    container_name: robot
    networks:
      testing_net:
        ipv4_address: 169.28.1.10
    command: managed-robot-app #call-puppet-app # managed-robot-app
    environment:
      GST_DEBUG: '*:3'
      OPENSSL_CONF: ''
      REGISTRY_HOST: envoy
      ROBOT_NAME: 'Robot in Docker'
      REGISTRY_PORT_FOR_AGENT: 10476
      REGISTRY_PORT_FOR_STORAGE: 10479
      REGISTRY_PORT_FOR_SIP_CHANNEL: 10480
    depends_on:
      - registry
      - envoy

  turn: 
    image: robolive-relay
    build:
      context: ./infra/playbook
      dockerfile: ./roles/relay/Dockerfile
    container_name: relay
    restart: always
    ports:
        - 8080:8080
        - 8080:8080/udp
        - 4443:4443
        - 45000-45100:45000-45100
        - 45000-45100:45000-45100/udp
    volumes:
        - "./tmp/config:/etc/coturn"
    networks:
        testing_net:
            ipv4_address: 169.28.1.4

  registry:
    image: robolive-registry
    build:
      context: .
      dockerfile: Dockerfile.allscala
      target: registry
    container_name: registry
    environment:
      REGISTRY_PORT_FOR_AGENT: 3476
      REGISTRY_PORT_FOR_INFO: 3477
      REGISTRY_PORT_FOR_CLIENT: 3478
      REGISTRY_PORT_FOR_STORAGE: 3479
      REGISTRY_PORT_FOR_SIP_CHANNEL: 3480
      VIDEO_SRC_FN: 'circles'
      SERVO_CONTROLLER: 'FAKE'
      SIGNALLING_URI: '169.28.1.1:9031' # '192.168.1.72:9031'
      STUN_URI: 'stun://169.28.1.4:8080' # 'stun://192.168.1.72:8080'
      TURN_URI: 'turn:rl.arigativa.ru:8080?transport=tcp' # 'turn:169.28.1.4:8080?transport=tcp'
    networks:
      testing_net:
        ipv4_address: 169.28.1.20

  envoy:
    image: envoyproxy/envoy-alpine:v1.16-latest
    ports:
      - 10476:10476 # registry agent
      - 10477:10477 # registry info
      - 10478:10478 # registry client
      - 10479:10479 # registry storage
      - 10480:10480 # registry sip channel
      - 9901:9901
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      testing_net:
        ipv4_address: 169.28.1.21

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 169.28.0.0/16
