version: '3'

services:
  signaling:
    image: kamailio-signalling
    container_name: kamailio-signalling
    ports:
      - "9030:9030"
      - "9031:9031"
      - "4443:4443"
    volumes:
      - ./tmp/config:/etc/kamailio
      - ./signalling/server/engine:/etc/kamailio/engine
    networks:
        testing_net:
            ipv4_address: 169.28.1.1
        
  turn: 
    container_name: coturn
    image: coturn
    restart: always
    ports:
        - 8080:8080
        - 4444:4444
        - 46000-46100:46000-46100
    volumes:
        - "./tmp/config:/etc/coturn"
    networks:
        testing_net:
            ipv4_address: 169.28.1.4


networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 169.28.0.0/16