version: '3.7'

services:
  signaling:
    image: robolive-signalling
    build:
      context: ./infra/playbook
      dockerfile: ./roles/signalling/Dockerfile
    container_name: signalling
    ports:
      - "9030:9030"
      - "9031:9031"
    volumes:
      - ./tmp/config:/etc/kamailio
      - ./signalling/server/engine:/etc/kamailio/engine
    networks:
        testing_net:
            ipv4_address: 169.28.1.1
        
  turn: 
    image: robolive-relay
    build:
      context: ./infra/playbook
      dockerfile: ./roles/relay/Dockerfile
    container_name: relay
    restart: always
    ports:
        - 8080:8080
        - 4443:4443
        - 46000-46100:46000-46100
    volumes:
        - "./tmp/config:/etc/coturn"
    networks:
        testing_net:
            ipv4_address: 169.28.1.4

  registry:
    build:
      context: .
      dockerfile: Dockerfile.allscala
      target: registry
    container_name: registry
    environment:
      REGISTRY_PORT_FOR_ROBOT: 3478
      REGISTRY_PORT_FOR_OPERATOR: 3479
    ports:
      - 3478:3478
      - 3479:3479


networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 169.28.0.0/16
