version: '3'

services:
  signaling:
    image: robolive-kamailio
    container_name: robolive-kamailio
    ports:
      - "9030:9030"
      - "9031:9031"
      - "4443:4443"
    volumes:
      - ./server:/etc/kamailio
    networks:
        testing_net:
            ipv4_address: 172.28.1.1


networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16