- name: Ensure package directory
  file:
    path: "{{ robolive_dir }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  tags:
    - frontend

- name: Ensure package directory
  file:
    path: "{{ frontend_package_dir }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  tags:
    - frontend

- name: Copy frontend package
  copy:
    src: "{{ frontend_package }}"
    dest: "{{ frontend_package_local }}"
    owner: root
    group: root
  tags:
    - frontend
  register: package_copy_result
  check_mode: no

- name: Extract frontend
  unarchive:
    src: "{{ frontend_package_local }}"
    dest: "{{ frontend_package_dir }}"
    remote_src: yes
    owner: root
    group: root
  when: package_copy_result.changed
  tags:
    - frontend
