robots:
  hosts:
    jetsonnano1.hsslb.ch:
      jetson_robot_user: alex
      jetson_robot_dir: "/home/alex/robot"
      jetson_robot_package: "/home/alex/dev/robolive/robot/target/universal/robot.zip"
      jetson_robot_package_remote: "/home/alex/robot.zip"
      jetson_robot_video_pipeline: "nvarguscamerasrc sensor_id=0 sensor_mode=3 ! video/x-raw(memory:NVMM),width=1280, height=720, framerate=60/1, format=NV12 ! nvvidconv flip-method=0 ! videoconvert ! videoscale ! video/x-raw,width=640,height=360"
      jetson_robot_name: "Hasseljet"
      jetson_robot_registry_address: "rl.arigativa.ru"
