signalling_enable_tls: true
signalling_conf_dir: /etc/kamailio
signalling_package_dir: /opt/kamailio

signalling_interface_ip: "{{ host_private_ip }}"
signalling_public_ip: "{{ host_public_ip }}"

# TODO: use dynamically set package built in this repository
#     | see:
#     |   * signalling/Dockerfile, README.md
#     |   * .github/workflows/kamailio-build.yml
signalling_kamailio_package: kamailio-distr.tar.gz

kamailio_home_directory: /home/kamailio
kamailio_user: kamailio
kamailio_group: kamailio
kamailio_private_memory: 256 # megabytes
kamailio_shared_memory: 256 #megabytes