inventory: local 
turn_external_ip: 127.0.0.1
turn_internal_ip: 169.28.1.4
turn_raw_port: 8080
turn_secure_port: 4443
turn_min_port: 46000
turn_max_port: 46100
turn_threads: 2
turn_username: test
turn_password: test
turn_realm: localhost
turn_cert: localhost.pem
turn_pkey: localhost.key
turn_config_dir: ../../tmp/config
turn_config_file: coturn.conf
turn_setup_nat: true
turn_service_enabled: false
turn_allow_loopback: true

signalling_conf_dir: ../../tmp/config
signalling_conf_ready_dir: /etc/kamailio
signalling_enable_tls: false
signalling_public_ip: 127.0.0.1
signalling_interface_ip: 169.28.1.1
signalling_ws_port: 9031
