---
- hosts: signalling_and_relay
  become: yes
  become_user: root
  roles:
    #- { role: geerlingguy.nginx, tags: nginx }
    - role: geerlingguy.java
      vars:
        java_packages:
          - openjdk-11-jdk
      tags: [ java ]
    - { role: relay, tags: [ relay ] }
    - { role: signalling, tags: [ signalling ] }
    - { role: registry, tags: [ registry ] }
    - { role: robolive_team, tags: [ robolive_team ] }
