name: 'Deployment & configuration of production environment'

on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/production.yml'
    branches:
      - master
  pull_request:
    paths:
      - 'infra/**'
      - '.github/workflows/production.yml'
  release:
    types:
      - released

jobs:
  terraform:
    name: 'Managing infrastructure'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/production
    steps: # TODO move this specific steps into single bash/make/whatever program to use it correctly from local as well
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setting up Terraform - infrastructure (VM's, network) provisioning tool
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 0.13.4

      - run: terraform init

      - run: terraform fmt -check

      - name: Calculating infrastructure changes
        if: github.ref != 'refs/heads/master' || github.event_name != 'push'
        run: terraform plan

      - name: Applying infrastrcture changes
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve

  ansible:
    name: 'Configuration of infrastructure (deployment of services)'
    runs-on: ubuntu-latest
    needs: terraform
    defaults:
      run:
        working-directory: infra/playbook
    env:
      ANSIBLE_HOST_KEY_CHECKING: False
    steps: # TODO move this specific steps into single bash/make/whatever program to use it correctly from local as well
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setting up Terraform - infrastructure (VM's, network) provisioning tool
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 0.13.4
          terraform_wrapper: false

      - run: terraform init # terraform needed to create ansible inventory, see: `signalling_and_relay.py`
        working-directory: infra/production

      - name: Setting up dependencies tooling
        run: sudo apt-get install python python-pip python-setuptools python-wheel ansible

      - name: Fix Ansible bug (https://github.com/ansible/ansible/issues/27793)
        run: rm -rf ~/.ansible/cp

      - name: Setting up Ansible environment
        run: pip install -r requirements.txt && ansible-galaxy role install -r requirements.yml

      - name: Define release_id
        id: determine_release_id
        run: |
          if ['${{ github.event_name }}' == 'release']
          then
              echo "::set-output name=result::${{ github.event.release.id }}"
          else
              echo "::set-output name=result::latest"
          fi

      - uses: dsaltares/fetch-gh-release-asset@aa37ae5c44d3c9820bc12fe675e8670ecd93bd1c
        with:
          repo: arigativa/robolive
          file: engine.tar.gz
          version: ${{ steps.determine_release_id.outputs.result }}
          token: ${{ secrets.RELEASES_GITHUB_TOKEN }}

      - uses: dsaltares/fetch-gh-release-asset@aa37ae5c44d3c9820bc12fe675e8670ecd93bd1c
        with:
          repo: arigativa/robolive
          file: registry.zip
          version: ${{ steps.determine_release_id.outputs.result }}
          token: ${{ secrets.RELEASES_GITHUB_TOKEN }}

      - uses: dsaltares/fetch-gh-release-asset@aa37ae5c44d3c9820bc12fe675e8670ecd93bd1c
        with:
          repo: arigativa/robolive
          file: webclient.tar.gz
          version: ${{ steps.determine_release_id.outputs.result }}
          token: ${{ secrets.RELEASES_GITHUB_TOKEN }}

      - name: Look what we've got
        run: ls -lah

      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "${{ github.workspace }}/ansible-variables.json"
          FILE_DATA: >-
            {
              "signalling_kamailio_engine_package": "${{ github.workspace }}/engine.tar.gz",
              "registry_package": "${{ github.workspace }}/registry.zip",
              "frontend_package": "${{ github.workspace }}/webclient.tar.gz"
            }

      - name: Check Ansible playbook
        run: ansible-playbook -i inventory/production -e '@${{ github.workspace }}/ansible-variables.json' playbook.yml -C -vv

      - name: Run Ansible playbook
        if: github.ref == 'refs/heads/master' || github.event_name == 'release'
        run: ansible-playbook -i inventory/production -e '@${{ github.workspace }}/ansible-variables.json' playbook.yml -vv

