name: Build registry

on:
  push:
    paths: # cat Dockerfile.allscala | grep -e '^ADD ' | awk '{print $2}'
      - 'build.sbt'
      - 'project/**'
      - 'sdp/**'
      - 'mjsip/**'
      - 'protocols/**'
      - 'registry/**'
      - '.github/workflows/**'
    branches:
      - master
  pull_request:
    paths:
      - 'build.sbt'
      - 'project/**'
      - 'sdp/**'
      - 'mjsip/**'
      - 'protocols/**'
      - 'registry/**'
      - '.github/workflows/**'
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10

      - run: sbt compile
      - run: sbt 'project registry' universal:packageBin

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: registry.zip
          path: registry/target/universal/registry.zip

  upload-artifact:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: registry.zip
          path: /tmp/
      - name: Upload signalling engine
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: /tmp/registry.zip
          asset_name: registry.zip
          asset_content_type: "application/zip"
