name: Build robot

on:
  push:
    paths: # cat Dockerfile.allscala | grep -e '^ADD ' | awk '{print $2}'
      - 'build.sbt'
      - 'project/**'
      - 'sdp/**'
      - 'mjsip/**'
      - 'protocols/**'
      - 'robot/**'
      - '.github/workflows/robot.yml'
    branches:
      - master
  pull_request:
    paths:
      - 'build.sbt'
      - 'project/**'
      - 'sdp/**'
      - 'mjsip/**'
      - 'protocols/**'
      - 'robot/**'
      - '.github/workflows/robot.yml'
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10

      - run: sbt compile
      - run: sbt 'project robot' universal:packageBin

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: robot.zip
          path: robot/target/universal/robot.zip

  upload-artifact:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: robot.zip
          path: /tmp/
      - name: Upload robot
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: /tmp/robot.zip
          asset_name: robot.zip
          asset_content_type: "application/zip"
