name: Build signalling server (engine)

on:
  push:
    paths:
      - 'signalling/server/engine/*'
      - 'signalling/server/engine/**'
      - '.github/workflows/signalling-engine-build.yml'
    branches: [ master ]
  pull_request:
    paths:
      - 'signalling/server/engine/*'
      - 'signalling/server/engine/**'
      - '.github/workflows/signalling-engine-build.yml'
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package server
        run: tar -czvf /tmp/engine.tar.gz -C signalling/server engine
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: engine.tar.gz
          path: /tmp/engine.tar.gz

  upload-artifact:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: engine.tar.gz
          path: /tmp/
      - name: Upload signalling engine
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: /tmp/engine.tar.gz
          asset_name: engine.tar.gz
          asset_content_type: "application/tar+gzip"
